### ISSUE TITLE
writeDictItems cannot overwrite

### ISSUE THREAD

**Issue by trieloff** [adobe/fastly-native-promises#27]
```
Trace: { Error: Duplicate dictionary_item: 'dictionary_id=3aT1oK0tdPlNo48E8TnhVx item_key=default service_id=6E6ge7REhiWetPCqy9jht2'
    at request.then (/code/helix-publish/node_modules/@adobe/fastly-native-promises/src/httpclient.js:32:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  data:
   { msg: 'Duplicate record',
     detail: 'Duplicate dictionary_item: \'dictionary_id=3aT1oK0tdPlNo48E8TnhVx item_key=default service_id=6E6ge7REhiWetPCqy9jht2\'' },
  status: 409,
  code: 'Duplicate record' }
    at Promise.all.then.catch (/code/helix-publish/src/publish.js:48:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
{ Error: Duplicate dictionary_item: 'dictionary_id=3aT1oK0tdPlNo48E8TnhVx item_key=default service_id=6E6ge7REhiWetPCqy9jht2'
    at request.then (/code/helix-publish/node_modules/@adobe/fastly-native-promises/src/httpclient.js:32:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  data:
   { msg: 'Duplicate record',
     detail: 'Duplicate dictionary_item: \'dictionary_id=3aT1oK0tdPlNo48E8TnhVx item_key=default service_id=6E6ge7REhiWetPCqy9jht2\'' },
  status: 409,
  code: 'Duplicate record' }
{ statusCode: 500,
  body:
   { status: 'Error',
     error: 'Error: Duplicate dictionary_item: \'dictionary_id=3aT1oK0tdPlNo48E8TnhVx item_key=default service_id=6E6ge7REhiWetPCqy9jht2\'',
     stack:
      [ 'Error: Duplicate dictionary_item: \'dictionary_id=3aT1oK0tdPlNo48E8TnhVx item_key=default service_id=6E6ge7REhiWetPCqy9jht2\'',
        '    at request.then (/code/helix-publish/node_modules/@adobe/fastly-native-promises/src/httpclient.js:32:17)',
        '    at <anonymous>',
        '    at process._tickCallback (internal/process/next_tick.js:188:7)' ] } }
```

**Comment by trieloff** [comment]
The underlying issue is that the dictionary is `write_only`:

`GET https://api.fastly.com/service/6E6ge7REhiWetPCqy9jht2/version/26/dictionary/strain_deny`
```http
HTTP/1.1 200 OK
Status: 200 OK
Content-Type: application/json
Cache-Control: no-cache
Accept-Ranges: bytes
Via: 1.1 varnish
Content-Length: 211
Accept-Ranges: bytes
Date: Tue, 22 Jan 2019 10:10:49 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-control-slwdc9035-CONTROL-SLWDC, cache-hhn1546-HHN
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1548151849.924595,VS0,VE489
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

{"version":26,"name":"strain_deny","deleted_at":null,"service_id":"6E6ge7REhiWetPCqy9jht2","created_at":"2019-01-22T09:46:25Z","write_only":true,"updated_at":"2019-01-22T09:46:25Z","id":"6YKIcQLobbr3ZNJXd6Wr0p"}
```

and then:

`GET https://api.fastly.com/service/6E6ge7REhiWetPCqy9jht2/dictionary/6YKIcQLobbr3ZNJXd6Wr0p/item/default`
```http
HTTP/1.1 400 Bad Request
Status: 400 Bad Request
Content-Type: application/json
Cache-Control: no-cache
Accept-Ranges: bytes
Via: 1.1 varnish
Accept-Ranges: bytes
Content-Length: 86
Accept-Ranges: bytes
Date: Tue, 22 Jan 2019 10:10:50 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-control-slwdc9037-CONTROL-SLWDC, cache-hhn1521-HHN
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1548151850.553670,VS0,VE469
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

{"msg":"Bad request","detail":"Not allowed to read contents of write_only dictionary"}
```

Therefore:

`POST https://api.fastly.com/service/6E6ge7REhiWetPCqy9jht2/dictionary/01zrr2NLhDsfCDwg02J3nY/item`
```http
HTTP/1.1 409 Conflict
Status: 409 Conflict
Content-Type: application/json
Cache-Control: no-cache
Fastly-RateLimit-Remaining: 867
Fastly-RateLimit-Reset: 1548154800
Accept-Ranges: bytes
Via: 1.1 varnish
Content-Length: 154
Accept-Ranges: bytes
Date: Tue, 22 Jan 2019 10:10:50 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-control-slwdc9036-CONTROL-SLWDC, cache-hhn1547-HHN
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1548151850.902627,VS0,VE494
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

{"msg":"Duplicate record","detail":"Duplicate dictionary_item: 'dictionary_id=01zrr2NLhDsfCDwg02J3nY item_key=default service_id=6E6ge7REhiWetPCqy9jht2'"}
```
